force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <description>For logging errors.</description>
    <label>Error Log</label>
    <nameField>
        <label>Error Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Line__c.field-meta.xml
<CustomField>
    <fullName>Line__c</fullName>
    <description>Line number where the error occurred</description>
    <label>Line</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Message describing the error</description>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Portfolio__c/Portfolio__c.object-meta.xml
<CustomObject>
    <description>An account may have a portfolio associated with it the includes information about the accounts management.</description>
    <label>Portfolio</label>
    <nameField>
        <label>Portfolio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portfolios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Portfolio__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <description>The portfolios color represents the importance of the related Account.</description>
    <label>Color</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Portfolio__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Unique External Id from other system</description>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/PortfolioIntegrationRestAPI.cls
@RestResource(urlMapping='/Portfolio/*')

global with sharing class PortfolioIntegrationRestAPI {

  @HttpPost
  global static ItemResponseWrapper doPost() {
    List<Portfolio__c> portfolios = new List<Portfolio__c>();
    List<Error_Log__c> errorLogs = new List<Error_Log__c>();
    RestRequest request = RestContext.request;
    RestResponse response = RestContext.response;
    ItemResponseWrapper responseStatus = new ItemResponseWrapper();

    try{
      String requestBody = request.requestBody.toString();
      Map<String, List<ItemWrapper>> requestBodyMap = (Map<String, List<ItemWrapper>>) JSON.deserialize(requestBody, Map<String, List<ItemWrapper>>.class);
      List<ItemWrapper> items = requestBodyMap.get('items');
    
      for(ItemWrapper item : items) {
        System.debug('item');
        System.debug(item);
        System.debug(item.color);
        portfolios.add(
          new Portfolio__c(
            Color__c = item.color,
            ExternalId__c = item.externalId
          )
        );
      }

      if(!portfolios.isEmpty()){
        insert portfolios;
      }

      responseStatus.Message = 'OK';
      responseStatus.statusCode = 200;

    } catch (Exception e) {
      errorLogs.add(
        new Error_Log__c (
          Name = 'portfolioIntegrationRestAPI.doPost',
          Message__c = e.getMessage(),
          Line__c = e.getLineNumber()
        )
      );
      insert errorLogs;
      
      responseStatus.Message = 'ERROR';
      responseStatus.statusCode = 500;
    }

    return responseStatus;
  }

  global class ItemWrapper {
    public String externalId;
    public String color;
  }

  global class ItemResponseWrapper {
    public String message;
    public Integer statusCode;
  }

}