force-app/main/default/objects/Portfolio__c/Portfolio__c.object-meta.xml
<CustomObject>
    <description>An account may have a portfolio associated with it the includes information about the accounts management.</description>
    <label>Portfolio</label>
    <nameField>
        <label>Portfolio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portfolios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Portfolio__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The account to which this portfolio belongs</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Portfolios</relationshipLabel>
    <relationshipName>Portfolios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Portfolio__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Unique External Id from other system</description>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/PortfolioHTTPCallout.cls
public class PortfolioHTTPCallout {

    public static List<Portfolio__c> portfolios = new List<Portfolio__c> ();

    @invocableMethod(callout=true label='CalloutForQTSystem' description='Sends information from updated portfolio objects to external system.')
    public static void getResponseFromExternalService(List<sObject> body) {
        portfolios = (List<Portfolio__c>) body;
        makeCallout();
    }

    public static HttpResponse makeCallout() {

        HttpRequest request = new HttpRequest();
        request.setHeader('Content-Type', 'application/json');
        request.setEndpoint('https://www.marcbenioff/v1/v2');
        request.setMethod('POST');
        
        RequestWrapper requestWrapper = new RequestWrapper();
        
        List<RequestItem> itemList = new List<RequestItem>();
        RequestItem temp = new RequestItem();
        
        for(Portfolio__c portfolio : portfolios){
            temp.accountId = portfolio.Account__c;
            temp.accountIdLink = portfolio.externalId__c;
            itemList.add(temp);
        }
        requestWrapper.items = itemList;
        String jsonData = JSON.serialize(requestWrapper);
        System.debug(jsonData);

        String expectedValue = jsonData;
        request.setBody(expectedValue); 
        Http http = new Http();
        HttpResponse response = http.send(request);

        return response;
       
    }

    // public static void getResponseFromExternalService(List<sObject> body) {

    //     HttpRequest request = new HttpRequest();
    //     request.setHeader('Content-Type', 'application/json');
    //     request.setEndpoint('https://www.marcbenioff/v1/v2');
    //     request.setMethod('POST');
        
    //     List<Portfolio__c> portfolios = (List<Portfolio__c>) body;
    //     RequestWrapper requestWrapper = new RequestWrapper();
        
    //     List<RequestItem> itemList = new List<RequestItem>();
    //     RequestItem temp = new RequestItem();
        
    //     for(Portfolio__c portfolio : portfolios){
    //         temp.accountId = portfolio.Account__c;
    //         temp.accountIdLink = portfolio.externalId__c;
    //         itemList.add(temp);
    //     }
    //     requestWrapper.items = itemList;
    //     String jsonData = JSON.serialize(requestWrapper);
    //     System.debug(jsonData);

    //     String expectedValue = jsonData;
    //     request.setBody(expectedValue); 
    //     Http http = new Http();
    //     HttpResponse response = http.send(request);
       
    // }

    public class RequestWrapper {
        public List<RequestItem> items; 
    }
    public class RequestItem {
        public String accountIdLink;
        public String accountId;
    }
}